# Use Node.js LTS version
FROM node:22.14.0-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

ENV NODE_ENV=development

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Start the application in development mode
CMD ["npm", "run", "dev"]